source "https://rubygems.org"

gem "capybara"
gem "capybara-screenshot"
gem "cucumber"
gem "gherkin"
gem "net-ssh"
gem "nokogiri"
gem "rspec"
gem "selenium-webdriver"
gem "site_prism"
gem "xpath"
gem "json"